// <auto-generated />
using System;
using GameOfLife.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfLife.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameOfLifeDbContext))]
    partial class GameOfLifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.BoardOutcomeRecord", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FixedPointAtGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchedThroughGeneration")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId");

                    b.ToTable("BoardOutcomes", (string)null);
                });

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.BoardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SeedCells")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SeedHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topology")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.GenerationSnapshotRecord", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Cells")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("StateHash")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "GenerationIndex");

                    b.ToTable("GenerationSnapshots", (string)null);
                });

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.BoardOutcomeRecord", b =>
                {
                    b.HasOne("GameOfLife.Infrastructure.Persistence.BoardRecord", "Board")
                        .WithOne("Outcome")
                        .HasForeignKey("GameOfLife.Infrastructure.Persistence.BoardOutcomeRecord", "BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.GenerationSnapshotRecord", b =>
                {
                    b.HasOne("GameOfLife.Infrastructure.Persistence.BoardRecord", "Board")
                        .WithMany("Snapshots")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("GameOfLife.Infrastructure.Persistence.BoardRecord", b =>
                {
                    b.Navigation("Outcome");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
