<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameOfLife.Application\GameOfLife.Application.csproj" />
    <ProjectReference Include="..\GameOfLife.Domain\GameOfLife.Domain.csproj" />
    <ProjectReference Include="..\GameOfLife.Infrastructure\GameOfLife.Infrastructure.csproj" />
  </ItemGroup>
</Project>
